"""Anthropic Claude integration used by the ``generate_brief`` graph node.

This module loads API credentials from environment and exposes a small wrapper
for concise study-brief generation.
"""

import os
from pathlib import Path

import anthropic
from dotenv import load_dotenv

load_dotenv(Path(__file__).parents[2] / ".env", override=True)

_SYSTEM_PROMPT = (
    "You are LARA, a personal study companion for Diego, an ML Engineer "
    "preparing for AI/ML and Sales Engineer roles. "
    "Diego's priority topics are: Gen AI System Design, DSA patterns (via AlgoMonster), "
    "RAG, agentic AI, and LangGraph. "
    "For DSA topics, focus on pattern recognition and when to apply the pattern — "
    "not solving from scratch. "
    "Generate briefs in plain text, no markdown. "
    "Focus on: what to review, what to practice, and common mistakes to avoid. "
    "Be concise — this is a companion, not a lesson. Maximum 150 words."
)


def _get_client() -> anthropic.Anthropic:
    """Create an authenticated Anthropic client from environment settings.
    Returns:
        ``anthropic.Anthropic`` API client.
    Raises:
        EnvironmentError: If ``ANTHROPIC_API_KEY`` is not configured.
    """
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        raise EnvironmentError("Missing required env var: ANTHROPIC_API_KEY")
    return anthropic.Anthropic(api_key=api_key)


def generate_brief(topic: str, duration_min: int, context: str) -> str:
    """Generate a focused study brief for a session.
    Args:
        topic: Study topic name.
        duration_min: Requested session length in minutes.
        context: Additional prompt context (for example weak areas).
    Returns:
        Brief text generated by Claude.
    """
    client = _get_client()
    prompt = (
        f"Topic: {topic}\n"
        f"Session duration: {duration_min} minutes\n"
        f"Context: {context}\n\n"
        "Generate a concise study brief for this session."
    )
    try:
        message = client.messages.create(
            model="claude-sonnet-4-6",
            max_tokens=1024,
            system=_SYSTEM_PROMPT,
            messages=[{"role": "user", "content": prompt}],
        )
    except anthropic.APIError as e:
        raise RuntimeError(f"Claude API error: {e}") from e

    return message.content[0].text


if __name__ == "__main__":
    brief = generate_brief(
        topic="System Design",
        duration_min=45,
        context="Practice questions",
    )
    print(brief)
